new colors added
NextChance/chatme-style-dictionary pull request #11
Opened 2019-04-01 13:26 UTC by JavierCabanas

2019-04-01 13:43 UTC, xavisson requested changes
Coral has changed too. It used to be "#ff5d5f"
And now it is defined as: #FA5A5A"

2019-04-02 08:40 UTC, virginiablesa reviewed
A parte del coral hay algún cambio más que faltaba por un problema con el Zeplin. Te lo comento abajo

2019-04-02 08:40 UTC, virginiablesa commented on properties/color/base.json
>        "value": "#7bcc1f"
He hablado con Miriam, parece que el Zeplin se había actualizado mal y había algún color que no se veía cambiado, es el caso de el melon:
```suggestion
      "value": "#60a90e"
```

2019-04-02 08:40 UTC, virginiablesa commented on properties/color/base.json
> +      "value": "#ff8912"
Lo mismo para el orange, el bueno es este:
```suggestion
      "value": "#fa915a"
```

2019-04-02 10:45 UTC, rafagarcia approved these changes
Por mi cuando los colores estén corregidos está OK.
Lo único: avisad cuando mergeeis porque tengo que volver a pedir la dependencia para actualizar nuestro proyecto.

2019-04-02 15:42 UTC, fdzsergio approved these changes

2019-04-03 12:39 UTC, merged